import type { Metadata } from "next";
import { Chewy } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";

const chewy = Chewy({
  subsets: ["latin"],
  display: "swap",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${chewy.className} antialiased h-full  flex-col min-h-dvh  flex bg-[url('/images/Background.svg')] bg-cover bg-no-repeat bg-Grey/900`}
      >
        <Navbar />
        <main className="h-full grid container flex-1 py-4">{children}</main>
      </body>
    </html>
  );
}
